third-year/computer-networks-security/assignment-www/server/app/app/src/apps/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/greeting_card/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from src.apps.greeting_card import views

app_name = "greeting_card"

urlpatterns = [
    path("", views.GreetingCardListView.as_view()),
    path("create", views.GreetingCardCreateView.as_view()),
    path("show/<str:token>", views.GreetingCardDetailView.as_view(), name="show"),
    path(
        "show-for-png/<str:token>",
        views.GreetingCardDetailForPNGView.as_view(),
        name="show-for-png",
    ),
    path(
        "download-png/<str:token>",
        views.GreetingCardDownloadPNGView.as_view(),
        name="download-png",
    ),
]

third-year/computer-networks-security/assignment-www/server/app/app/src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("src.apps.greeting_card.urls", namespace="greeting-card")),
    path("accounts/", include("src.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    footer = models.CharField(max_length=1024)

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/greeting_card/models.py
import binascii
import os

from django.contrib.auth.models import User
from django.db import models
from django.db.models import SET_NULL
from django.urls import reverse


class GreetingCard(models.Model):
    token = models.CharField(max_length=255)
    recipient = models.TextField()
    sender = models.ForeignKey(User, on_delete=SET_NULL, null=True)
    content = models.TextField()
    template = models.TextField()
    read = models.BooleanField(default=False)

    def update_token_if_needed(self):
        if not self.token:
            self.token = binascii.hexlify(os.urandom(32)).decode("ascii")

    def get_absolute_url(self):
        return reverse("greeting-card:show", args=[self.token])

    def save(self):
        self.update_token_if_needed()
        super().save()

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    footer = forms.TextInput()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        error_messages = {
            "username": {
                "unique": "Użytkownik o podanej nazwie już istnieje.",
            }
        }

    error_messages = {
        "password_mismatch": "Podane hasła się nie zgadzają.",
    }

    def save(self, commit=True):
        footer = self.data["footer"]
        # Save user first
        user = super().save(commit=True)
        profile = Profile.objects.create(user=user)
        profile.footer = footer
        profile.save()
        return user

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/greeting_card/forms.py
from django import forms


class GreetingCardForm(forms.Form):
    recipient = forms.TextInput()
    content = forms.TextInput()

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import RegisterForm


class SignUpView(generic.CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

third-year/computer-networks-security/assignment-www/server/app/app/src/apps/greeting_card/views.py
import subprocess
import tempfile

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic
from src.apps.greeting_card.models import GreetingCard

from .utils import render_card


class GreetingCardListView(LoginRequiredMixin, generic.ListView):
    template_name = "greeting_card/list.html"
    model = GreetingCard

    def get_queryset(self, *args, **kwargs):
        objects = GreetingCard.objects.filter(recipient=self.request.user.username)
        if self.request.GET.get("unread", None) is not None:
            objects = objects.filter(read=False)
        return objects

    def get_context_data(self, **kwargs):
        context = super(GreetingCardListView, self).get_context_data(**kwargs)
        context["all"] = self.request.GET.get("unread", None) is None
        return context


class GreetingCardCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "greeting_card/create.html"
    model = GreetingCard
    fields = ["recipient", "content", "template"]

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super().form_valid(form)


class GreetingCardDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "greeting_card/detail.html"
    model = GreetingCard

    slug_url_kwarg = "token"
    slug_field = "token"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if self.request.user.username == self.object.recipient:
            self.object.read = True
        self.object.save()
        return response

    def get_context_data(self, **kwargs):
        context = super(GreetingCardDetailView, self).get_context_data(**kwargs)
        rendered = render_card(self.object)
        context["content"] = rendered
        return context


class GreetingCardDetailForPNGView(generic.DetailView):
    template_name = "greeting_card/detail_for_png.html"
    model = GreetingCard

    slug_url_kwarg = "token"
    slug_field = "token"

    def get_context_data(self, **kwargs):
        context = super(GreetingCardDetailForPNGView, self).get_context_data(**kwargs)
        rendered = render_card(self.object)
        context["content"] = rendered
        return context


class GreetingCardDownloadPNGView(LoginRequiredMixin, generic.View):
    model = GreetingCard

    def get(self, request, token):
        file_name = tempfile.mktemp(suffix=".png")
        subprocess.call(
            [
                "chromium",
                "--headless",
                "--disable-gpu",
                "--no-sandbox",
                "--screenshot=" + file_name,
                "http://127.0.0.1:3000/show-for-png/" + token,
            ]
        )
        with open(file_name, "rb") as f:
            return HttpResponse(f.read(), content_type="image/png")

third-year/computer-networks-security/assignment-www/server/app/app/src/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="/static/index.css" />
        <link href="https://fonts.googleapis.com/css2?family=Fasthand&display=swap" rel="stylesheet">
        <script src="/static/tinymce/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>

        {% block head_additional %}
        {% endblock %}
    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

third-year/computer-networks-security/assignment-www/server/app/app/src/templates/greeting_card/create.html
{% extends "base.html" %}

{% block head_additional %}
    <script>
        window.onload = function() {
            tinymce.init({
                menubar: false,
                statusbar: false,
                selector: '#content'
            });
        }
    </script>
{% endblock %}

{% block content %}
    <div class="main">
        <h1>E-kartka na każdą uroczystość</h1>
        <p>
            Stwórz w mgieniu oka piękną i wzruszającą kartkę, którą prześlesz komu chcesz!
        </p>

        <form action="" method="POST">
            {% csrf_token %}

            <input type="text" name="recipient" class="form-control" placeholder="Odbiorca" required>
            <small class="form-text">Kartka zostanie przesłana użytkownikowi o tej nazwie.</small>
            <textarea name="content" class="form-control" placeholder="Treść" id="content"></textarea>
            <label>Motyw</label>
            <select name="template" class="form-control" aria-label="Szablon">
              <option value="normal" selected>Zwykły</option>
              <option value="coffee">Kawa</option>
            </select>
            <input type="submit" value="Utwórz" />
        </form>
    </div>
{% endblock %}

third-year/computer-networks-security/assignment-www/server/app/app/src/templates/greeting_card/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="main">
        <div class="content">
            {{ content | safe }}
        </div>

        <div class="mt-20">
            <a href="{% url 'greeting-card:download-png' object.token %}">Pobierz jako PNG</a> /
            <a href="/create">Stwórz inną kartkę</a>
        </div>
    </div>
{% endblock %}

third-year/computer-networks-security/assignment-www/server/app/app/src/templates/greeting_card/detail_for_png.html
{% extends "base.html" %}

{% block content %}
    <div class="main">
        <div class="content">
            {{ content | safe }}
        </div>
    </div>
{% endblock %}

third-year/computer-networks-security/assignment-www/server/app/app/src/templates/greeting_card/list.html
{% extends "base.html" %}

{% block content %}
    <div class="main">
        <h2>Kartki dla Ciebie</h2>
        <a href="/create">Stwórz nową kartkę</a>
        <div style="margin-top: 15px">
            {% if all %}
                <a href="/?unread">Pokaż nieprzeczytane</a>
            {% else %}
                <a href="/">Pokaż wszytkie</a>
            {% endif %}
        </div>
        <ul>
            {% for object in object_list %}
                <li><a href="/show/{{ object.token }}">Kartka od {{ object.sender.username }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}